[package]
name = "compiler"
version = "0.1.0"

[dependencies]
ast = { path = "../ast" }
host = { path = "../host" }
model = { path = "../model" }
parse = { path = "../parse" }
util = { path = "../util" }
lazy_static = "0.2"
