hard_tabs = true

array_width = 110
comment_width = 110
max_width = 110
struct_lit_width = 110
struct_variant_width = 110
fn_call_width = 110

attributes_on_same_line_as_field = false
attributes_on_same_line_as_variant = false

# Always use block indent
closure_block_indent_threshold = 0
combine_control_expr = false

imports_indent = "Visual"

match_pattern_separator_break_point = "Front"
multiline_match_arm_forces_block = true

reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true

trailing_semicolon = false
wrap_match_arms = false
