[package]
name = "compile"
version = "0.1.0"

[dependencies]
ast = { path = "../ast" }
check = { path = "../check" }
host = { path = "../host" }
model = { path = "../model" }
parse = { path = "../parse" }
util = { path = "../util" }
