[package]
name = "parse"
version = "0.1.0"

[dependencies]
lazy_static = "0.2"
phf = "0.7.21"
phf_macros = "0.7.21"

ast = { path = "../ast" }
parse_diag = { path = "../parse_diag" }
util = { path = "../util" }
