<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Noze</string>
    <key>scopeName</key>
    <string>source.noze</string>
    <key>fileTypes</key>
    <array>
      <string>nz</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>match</key>
        <string>^\s*(abstract|fun|def|var|val)\s+([A-Z][a-zA-Z0-9\-]*)\s+([a-zA-Z0-9\-]*)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.type</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.quoted</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>match</key>
        <string>^\s*impl\s+([A-Z][a-zA-Z0-9\-]*)\.([a-zA-Z0-9\-]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type</string>
        <key>match</key>
        <string>\b[A-Z][a-zA-Z0-9\-]*\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>match</key>
        <string>\b(_|abstract|assert|catch|def|do|else|enum|false|finally|for|fun|generic|get|if|io|is|impl|import|in|new|pass|recur|self|set|slots|then|true|try|val|var|when|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\+|\-|\*|\/)[^a-zA-Z0-9-]</string>
      </dict>
      <dict>
        <key>name</key>
        <string/>
        <key>match</key>
        <string>\b[a-z][a-zA-Z0-9\-]*\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>\.|\,|=|\\</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>match</key>
            <string>\{([^}])\}</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.interpolated</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>\|\|?\s.*</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>^\s*(region)[^\n]*\n</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>^\s*(todo)[^\n]*\n</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>[\(\[\]\)\{\}]</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>[\+\-]?((0((b[01]+)|(o[0-8]+)|(x[\da-f]+)))|(\d+(\.\d+)?))</string>
      </dict>
    </array>
  </dict>
</plist>